version: '2.2'
services:
  geth:
    build:
        context: docker_files
        dockerfile: Dockerfile.geth
    entrypoint: /bin/sh /run.sh geth
    ports:
      - 0.0.0.0:8546:8546
    environment:
      - PRIVATE_KEY=dcc958317af5acf282fb2cf5324c433c69d4041014a3c4f154f742d32e8f840d
      - ETHERBASE=0x6120a30e955b6dd99c9adc6e1ece6dcc6d48a53f
  postgres:
    image: postgres:9.5
    ports:
      - 0.0.0.0:5432:5432
    environment:
      - POSTGRES_USER=7d3690ead19b8
      - POSTGRES_PASSWORD=c818a4f0c5125vf
      - POSTGRES_DB=faktur
