version: '2.2'
services:
  geth:
    build:
        context: docker_files
        dockerfile: Dockerfile.geth
    entrypoint: /bin/sh /run.sh geth
    environment:
      - PRIVATE_KEY=dcc958317af5acf282fb2cf5324c433c69d4041014a3c4f154f742d32e8f840d
      - ETHERBASE=0x6120a30e955b6dd99c9adc6e1ece6dcc6d48a53f
  fakturdaemon:
    build: .
    environment:
      - RPC_URL=ws://geth:8546/
      - PRIVATE_KEY=dcc958317af5acf282fb2cf5324c433c69d4041014a3c4f154f742d32e8f840d # 0x6120a30e955b6dd99c9adc6e1ece6dcc6d48a53f
      - CHAIN_ID=29957
      - CONTRACT=0x0
      - DB_DSN=host=postgres user=7d3690ead19b8 dbname=faktur sslmode=disable password=c818a4f0c5125vf
    ports:
      - 127.0.0.1:8090:8090
    links:
      - postgres

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=7d3690ead19b8
      - POSTGRES_PASSWORD=c818a4f0c5125vf
      - POSTGRES_DB=faktur
